### PR TITLE
Props will be handed to <Element>

### PR DESCRIPTION
**Pull request by miallo**
PR to #22 
I did not test this until now. I might do it later this weekend. Otherwise, anyone can feel free to take a look as well!

### CODE REVIEW

**Comment by miallo** [comment]
Sorry, apparently it was a bit late yesterday and I didn't think about titles anymore...

**Comment by miallo** [comment]
@devshawn I guess it is done?
Will you release this version anytime soon?

**Comment by devshawn** [comment]
Thanks @miallo! I'll take a look tonight and get a release built and published.

**Comment by devshawn** [comment]
Apologies @miallo for not getting to this -- will handle it today. Thanks!

**Comment by miallo** [comment]
No problem ;) Until the release, our project will just use our branch instead.

**Review by devshawn — APPROVED** [review]

**Comment by devshawn** [comment]
@miallo - Released as 0.2.0 :)

**Pull request merged**
